# Generated by Django 3.0.3 on 2020-07-04 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='items',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
