# Generated by Django 3.0.3 on 2020-07-06 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_items_pdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8)),
                ('date', models.DateField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
