# Generated by Django 3.0.3 on 2020-07-06 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0006_auto_20200706_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='language',
            field=models.CharField(choices=[('UA', 'UA'), ('RU', 'RU')], default='RU', max_length=256),
        ),
    ]
