# Generated by Django 3.0.3 on 2020-07-06 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0008_auto_20200706_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='description_ua',
            field=models.TextField(blank=True, null=True),
        ),
    ]
