# Generated by Django 3.0.3 on 2020-07-06 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0009_items_description_ua'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcode',
            old_name='description',
            new_name='description_ru',
        ),
    ]
