# Generated by Django 3.0.3 on 2020-07-06 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0011_productcode_description_ua'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photos',
            old_name='description',
            new_name='description_ru',
        ),
    ]
