# Generated by Django 3.0.3 on 2020-07-06 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0012_auto_20200706_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos',
            name='description_ua',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
