# Generated by Django 3.0.3 on 2020-07-16 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0014_auto_20200706_2113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='pdf',
            new_name='pdf_1',
        ),
        migrations.AddField(
            model_name='items',
            name='pdf_2',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='items',
            name='pdf_3',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='productcode',
            name='owner',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
