# Generated by Django 3.0.3 on 2020-08-04 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0016_spy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spy',
            name='attempts',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
