# Generated by Django 3.0.3 on 2023-04-08 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0017_auto_20200805_0001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='language',
        ),
        migrations.AddField(
            model_name='items',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='photos',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='photos',
            name='description_ru',
            field=models.TextField(blank=True, null=True),
        ),
    ]
