# Generated by Django 4.2 on 2023-04-20 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0018_auto_20230408_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='qty',
            field=models.IntegerField(default=0, verbose_name='Наявна кількість'),
        ),
        migrations.AlterField(
            model_name='items',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Опис англійською'),
        ),
        migrations.AlterField(
            model_name='items',
            name='description_ua',
            field=models.TextField(blank=True, null=True, verbose_name='Опис українською'),
        ),
        migrations.AlterField(
            model_name='items',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Назва продукту'),
        ),
        migrations.AlterField(
            model_name='items',
            name='pdf_1',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Інструкція українською'),
        ),
        migrations.AlterField(
            model_name='items',
            name='pdf_2',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Інструкція російською'),
        ),
        migrations.AlterField(
            model_name='items',
            name='pdf_3',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Інструкція англійською'),
        ),
        migrations.AlterField(
            model_name='items',
            name='price',
            field=models.FloatField(verbose_name='Ціна'),
        ),
        migrations.AlterField(
            model_name='items',
            name='sale',
            field=models.FloatField(blank=True, null=True, verbose_name='Розпродаж'),
        ),
        migrations.AlterField(
            model_name='photos',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Опис англійською'),
        ),
        migrations.AlterField(
            model_name='photos',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Опис російською'),
        ),
        migrations.AlterField(
            model_name='photos',
            name='description_ua',
            field=models.TextField(blank=True, null=True, verbose_name='Опис українською'),
        ),
        migrations.AlterField(
            model_name='photos',
            name='image',
            field=models.ImageField(upload_to='items', verbose_name='Зображення'),
        ),
        migrations.CreateModel(
            name='Parts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='Назва')),
                ('picture', models.ImageField(upload_to='parts', verbose_name='Зображення')),
                ('url_1', models.URLField(blank=True, null=True, verbose_name='Посилання №1')),
                ('url_2', models.URLField(blank=True, null=True, verbose_name='Посилання №2')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='Ціна за одиницю')),
                ('qty', models.IntegerField(verbose_name='Кількість на складі')),
                ('item', models.ManyToManyField(to='item.items')),
            ],
            options={
                'verbose_name': 'Part',
                'verbose_name_plural': 'Parts',
            },
        ),
    ]
