# Generated by Django 3.0.3 on 2023-06-03 07:13

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0019_items_qty_alter_items_description_en_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='items',
            options={'verbose_name': 'Part', 'verbose_name_plural': 'Продукція'},
        ),
        migrations.AlterModelOptions(
            name='parts',
            options={'verbose_name': 'Part', 'verbose_name_plural': 'Комплектуючі'},
        ),
        migrations.AlterField(
            model_name='items',
            name='description_en',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Опис англійською'),
        ),
        migrations.AlterField(
            model_name='items',
            name='description_ru',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='description_ua',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Опис українською'),
        ),
    ]
